Feature header - Updates for Desktop design AEMCEDS-31
AEM-COMP/aem-competency pull request #13
Opened 2024-05-14 05:50 UTC by Abhishek301983

Please always provide the [AEMCEDS-31] your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #<jira-issue-id>

Test URLs:
- Before: https://main--aem-competency--aem-comp.hlx.live/Drafts/Mohit/sections
- After: https://feature-header--aem-competency--aem-comp.hlx.live/Drafts/Mohit/sections

- [ ]  **If you are adding a new block or a variation to an existing block**, please fill below:

  Block library path: https://<branch>--aem-competency--aem-comp.hlx.live/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/<your-block>&index=0

2024-05-20 11:01 UTC, mkbansal1 requested changes
- Mobile view is totally broken
- Desktop view > dropdown hover effects are missing
- Desktop > down icon animation on hover is different from designs

2024-05-20 11:01 UTC, mkbansal1 commented on styles/styles.css
> +  text-decoration: none;
revert this rule, text decoration should underline for site, block specific experience should be overridden in block css.

2024-05-20 11:01 UTC, mkbansal1 commented on blocks/header/header.js
> +  if (window.innerWidth < 1280) {
Akash has added a utility method in utils.js to check if viewport is desktop, use that

2024-05-20 11:01 UTC, mkbansal1 commented on blocks/header/header.css
> +@media (width < 1279px) {
mobile view is <=1279

2024-05-20 11:01 UTC, mkbansal1 commented on blocks/header/header.css
> +      background-color: black;
Use variables instead of using colors directly

2024-05-20 11:01 UTC, mkbansal1 commented on blocks/header/header.css
The background color should be transparent.
`background-color: transparent`

```
header nav .nav-hamburger button {
  height: 22px;
  margin: 0;
  border: 0;
  border-radius: 0;
  padding: 0;
  background-color: var(--background-color);
  color: inherit;
  overflow: initial;
  text-overflow: initial;
  white-space: initial;
}
```

2024-05-20 12:15 UTC, Abhishek301983 commented on blocks/header/header.js
> +  if (window.innerWidth < 1280) {
Updated

2024-05-20 12:16 UTC, Abhishek301983 commented on blocks/header/header.css
> +      background-color: black;
Updated

2024-05-20 12:16 UTC, Abhishek301983 commented on blocks/header/header.css
Updated

2024-05-20 12:16 UTC, Abhishek301983 commented on blocks/header/header.css
> +@media (width < 1279px) {
Updated

2024-05-29 18:56 UTC, mrugesh-adobe commented
Desktop and Mobile UI issues are been fixed.

Attaching the screenshot of the same.

<img width="947" alt="desktop" src="https://github.com/AEM-COMP/aem-competency/assets/159900947/efbd8510-cb97-42bc-9bda-1335d5199577">

<img width="728" alt="mobile-view" src="https://github.com/AEM-COMP/aem-competency/assets/159900947/31bb4ed1-291c-4e20-a6d7-534724ed292d">

2024-05-30 20:10 UTC, mrugesh-adobe approved these changes

2024-05-30 20:11 UTC, mrugesh-adobe commented
> * Mobile view is totally broken
> * Desktop view > dropdown hover effects are missing
> * Desktop > down icon animation on hover is different from designs

Fixes are done.

2024-05-31 05:21 UTC, mrugesh-adobe commented
<img width="475" alt="image" src="https://github.com/AEM-COMP/aem-competency/assets/159900947/18f71ccd-ae03-4c89-b8a9-878e0101bd6d">

2024-05-31 05:31 UTC, mkbansal1 approved these changes

2024-05-31 05:38 UTC, mrugesh-adobe commented
<img width="840" alt="image" src="https://github.com/AEM-COMP/aem-competency/assets/159900947/7050a3b2-4874-45b9-b9ec-cdafecd71a9f">
<img width="421" alt="image" src="https://github.com/AEM-COMP/aem-competency/assets/159900947/86bdd630-7b27-40ed-865c-2aa92b7416dc">

2024-05-31 05:39 UTC, merged